### ISSUE TITLE
Manage labels - feature request

### ISSUE THREAD

**Issue by slickrick1983** [codetree/feedback#82] opened 2015-06-03 13:11 UTC
Currently codetree doesnt allow you to add the same labels accross repo's.
I would like a screen similar to the milestone screen were I can manage the labels accross repo's

**Comment by rinopo** [comment] 2015-06-03 14:40
+1

**Comment by derrickreimer** [comment] 2015-06-03 15:58
Thanks gents. cc'd you on the original label management issue.

Duplicate of #68

**Closed as completed by derrickreimer** 2015-06-03 15:58 UTC
Labels: duplicate, In Review
