### ISSUE TITLE
Issues randomly go blank

### ISSUE THREAD

**Issue by chadfawcett** [codetree/feedback#282] opened 2018-10-22 20:32 UTC
Often when scrolling though the list of issues they will all go blank for that column.

Sometimes it's after I open an issue and then close the modal.

**Chrome Version 70.0.3538
Mac OS**

![screen shot 2018-10-22 at 1 27 18 pm](https://user-images.githubusercontent.com/3250463/47317490-897ed400-d5fe-11e8-9a36-52d5b803b9fa.png)

**Comment by rstocker99** [comment] 2018-10-29 18:55
That's not great. I've filed a bug. That said we are having some trouble reproducing this one. Next time you run into it any chance you open up the Chrome Dev tools and see if there is an error you can paste in. Thanks.

**Comment by chadfawcett** [comment] 2018-10-29 22:17
There weren't any errors related to the cards disappearing, but there is a CORS issue related to your fonts that show up when the page is first loaded.

![screen shot 2018-10-29 at 3 14 20 pm](https://user-images.githubusercontent.com/3250463/47683698-99ae2a80-db8d-11e8-9c5f-3a475e244f3d.png)

**Comment by rstocker99** [comment] 2018-10-29 23:17
Thanks for the CORS issue. Filed.

That said we still can't reproduce this one. We're not seeing that issue on the same Chrome build on MacOS. Are there any other repro steps you can offer up? Any particular Chrome Extension you are running? Is it all cards regardless of column?

**Comment by chadfawcett** [comment] 2018-10-29 23:45
Upon further investigation trying to replicate, it turns out it's actually happening on a hover. If I hover on an the icon of an `unassigned` issue, everything goes blank.

![invisible cards 2](https://user-images.githubusercontent.com/3250463/47686727-eac41b80-db99-11e8-8a01-db196efee74a.gif)

Also if I hover over a PR number they go blank.

![invisible cards 1](https://user-images.githubusercontent.com/3250463/47686740-fc0d2800-db99-11e8-8df6-7b1c4f1ca2fa.gif)

**Comment by rstocker99** [comment] 2018-10-30 23:30
Thanks for the extra repro info. Looks like it's related to showing tooltips. Sadly I still can't reproduce it on our end.

Do you see similar behaviour in other places that show tooltips e.g. the edit issue model or in the list view when you go over the hamburger menu or is it just on cards in the board view? 

![](http://g.recordit.co/5f2rCxqgyS.gif)

or

![](http://g.recordit.co/1BlBP8prqL.gif)

**Comment by chadfawcett** [comment] 2018-10-30 23:34
Neither of those ones cause issues. So far it's just tooltips within the card lists.

**Comment by rstocker99** [comment] 2018-10-30 23:37
Ok, I've filed a bug but I'm not holding my breath on a quick fix for this one. Sorry :(.

**Comment by chadfawcett** [comment] 2018-10-30 23:39
This bug is becoming more interesting haha. It seems like it's only when the lists expand past the width of the screen.

![invisible cards 3](https://user-images.githubusercontent.com/3250463/47757143-4954cc80-dc62-11e8-901c-f656f8a8dd1d.gif)

**Comment by rstocker99** [comment] 2018-10-31 00:30
Well that's one more piece of info. Thanks for sharing that! I got excited that shrinking my view port would help with the repro but alas still doesn't repro for me. Thanks for the help trying to track it down. If you're up for one more peek do you see anything interesting in the inspector when you make a tool tip show?

![](http://g.recordit.co/zyPj5ORZWv.gif)

**Comment by chadfawcett** [comment] 2018-10-31 05:52
What an elusive bug! I'm finally in the same boat as you. I'm no longer able to replicate it.

One more slight bug, but not nearly as big of a deal. I noticed the tooltip sometimes gets cut off.
<img width="286" alt="screen shot 2018-10-30 at 10 51 22 pm" src="https://user-images.githubusercontent.com/3250463/47768734-86d34d00-dc96-11e8-938d-602cdde8bc2b.png">

**Comment by chadfawcett** [comment] 2018-10-31 19:59
Haha okay, so I'm replicating the issue again. This may or may not be related, but it seems to only replicate if the "Update your payment info" sticky is visible on the bottom left. After removing it, the cards comes back and the tooltips behave as expected.

![invisible cards 4](https://user-images.githubusercontent.com/3250463/47815131-b45add80-dd0c-11e8-808d-9bdec4a487bc.gif)

**Comment by misskniss** [comment] 2019-01-17 23:16
I am also seeing this issue (and also have the 'Update your payment...' tip open).

**Comment by ac21** [comment] 2019-11-02 03:14
closing issue as it is no longer occuring

**Closed as completed by ac21** 2019-11-02 03:14 UTC
Labels: bug
