### ISSUE TITLE
Delayed workflow/stages tag modification causing issues

### ISSUE THREAD

**Issue by kangaroo5383** [codetree/feedback#212] opened 2016-08-03 20:12 UTC
Codetree has been really great after many months of usage, however there has been one important issue that has been causing some problems for us.

On issue closing, "in progress" tags are suppose to be removed, and we manually add the "release" tag pending release of the current version.  There has been a handful of times where the close issue action update from codetree (removing stage tags) wasn't executed until quite awhile after relevant tags were added manually.  This caused these new tags to be removed erroneously.

One fix I would propose is to not modify any stage tags added after an issue was closed.

Steps to repro:
1. add stage tag "In Progress" 
2. close issue
3. immediately add stage tag "Release"

result:  Sometimes the "Release" tag is removed after some time has passed
expected: "Release" tag is not removed 

Thanks for looking into it!

**Comment by kareem** [comment] 2016-08-03 23:44
Hey @kangaroo5383 thanks for the kind works and issue report.  I'll pass it on to the team to take a look at.

**Comment by kareem** [comment] 2016-08-25 19:15
@kangaroo5383 Looking at this in more depth -- just want to confirm that the release label is NOT a custom Codetree stage.  Is that correct?

**Comment by kareem** [comment] 2016-08-25 19:16
Also do you add the release tag in Codetree or Github, or either depending on the dev / situation?

**Comment by kangaroo5383** [comment] 2016-08-25 19:19
Release label is a custom stage

We current have been adding the release tag in Github manually.  Ideally, when an issue is closed (via commits `closes #123`) it would automatically change from `resolved` to `release`.  

![image](https://cloud.githubusercontent.com/assets/34344/17982683/d8679434-6abd-11e6-9917-282b33b926eb.png)

**Comment by kareem** [comment] 2016-08-25 19:38
Hmm, Closed issues are intended to be at the end of your workflow, but it looks like some of your issues go Closed -> Release -> Fixed.  Is that right?  

If so can you help us understand how you use this workflow?  The intention is that custom stage labels get removed when an issue is Closed so the system is currently working as designed.  Open to changing it with new info, but don't totally understand your use case yet.  Thanks.

**Comment by kareem** [comment] 2016-08-25 20:08
Going to close this as it's related to #191.  Let's move the discussion there ok @kangaroo5383?

**Comment by kareem** [comment] 2016-08-26 18:58
Hi @kangaroo5383, I think we have a quicker workaround for you.  

You'd modify your Codetree workflow to look like this:

in progress / open
resolve / open (in code review)

You'd remove these stages from your **Codetree** workflow:

release / closed (issue is completed and will go out with the next release)
fixed / closed (in the latest internal build, assigned to issue creator to verified)

The release and fixed labels would stay in GitHub (and Codetree).  You can assign them to closed tickets and Codetree won't remove them - Codetree only removes custom stage labels from an issue when it moves from one stage to another.

The key issue is making sure the close action in Codetree gets to GitHub faster.  We have some thoughts on how to do that and have ticketed them.

Let me know how that sounds.  Thx!

**Comment by kangaroo5383** [comment] 2016-08-30 19:53
Thanks for the follow up, yeah I think removing `release` and `fixed` label from the codetree stages would work as a workaround. 👍

**Comment by kareem** [comment] 2016-08-30 19:59
Awesome.  Going to close this ticket for now.

**Closed as completed by kareem** 2016-08-30 19:59 UTC
Labels: In Review
