### ISSUE TITLE
Issue Rules: when an issue is closed, the label tagging happens from a different user

### ISSUE THREAD

**Issue by haikalpribadi** [codetree/feedback#274] opened 2018-09-24 13:16 UTC
Hi CodeTree team,

We're using the Issue Rules: when an issue is closed, "Add label solved". Like the screenshot below:

![Issue Rules: when an issue is closed, add label "solved"](https://user-images.githubusercontent.com/567679/45954099-fdc85680-c003-11e8-9ff7-54c81e53f14f.png)

However, the when the "solved" label is added to the issue, it was made through a different user account than the user who closed the issue. For example, see the screenshot below:\

![screen shot 2018-09-24 at 14 15 13](https://user-images.githubusercontent.com/567679/45954209-4c75f080-c004-11e8-809b-418bf63b3d03.png)
You can see the issue here: https://github.com/graknlabs/grakn/issues/1991

I believe this is a bug? Can we fix it so that the user that adds the label "solved" is the same user as who closed the issue?

Thank you!

**Comment by arifb** [comment] 2018-09-25 04:29
Hi @haikalpribadi. This is definitely not ideal but by way of explanation, Codetree currently is a OAuth GitHub app, which uses the GH account of the person who signed up for Codetree to post to GH. We have an issue on our end to move to a GitHub App which would add activities in GH as Codetree or a bot-user.

I know you're asking us to use the same user who closed the issue but there are some actions and cases where this would not be possible - for example, a user closed the issue who is part of the repo but is not a Codetree user. In that case we wouldn't have their OAuth creds in order to perform actions as them.

Because of limitations like this we chose to have a common user to perform all automated actions.

Again, we feel the best solution would be to have a bot account or similar to do these actions, and that's what moving to a GitHub app would give us. It's on our list.

**Comment by haikalpribadi** [comment] 2018-09-25 14:29
Hi @arifb, thanks for the explanation. We do have a bot account that could be configured to be the "automator". And in fact, `Irtazaraza` (who's account is currently used) is not actually the user who signed up too.

> this would not be possible - for example, a user closed the issue who is part of the repo but is not a Codetree user

I see, and I understand that things are never as simple as they sound :) but what about a simple check "if `user` is in codetree, use `user`, else pick an admin user from codetree" ?

**Comment by arifb** [comment] 2018-09-30 15:12
Hi @haikalpribadi, thanks. Yes, the conditional check whether the user has OAuth to Codetree, use her, and if not, use another user who does should work.

We built workflow with the goal to soon move to GithHub apps for authentication, and thus would have a 'codetree-bot' user or similar to do these things.

We'll have to discuss internally whether we want to wait for the move to GitHub apps or use that algorithm described above.

In the meantime, feel free to tell me which user you'd like to be used instead of `Irtazaraza` and I can make that change. Reach out via intercom when on Codetree or use help@codetree.com (just for privacy reasons, instead of dropping it in a public issues repo here).

**Comment by haikalpribadi** [comment] 2018-10-01 12:38
hi @arifb, thanks for reviewing this! (I've also updated the comment above to make it more readable, I missed a new line after the quote).

In the meantime, if you can use @grabl as the user for any automation, that would be really helpful. It is our bot account that already does lots of automation on our repositories.

**Comment by arifb** [comment] 2018-10-01 13:45
Hi @haikalpribadi, I've reviewed the code just now, even though I wrote it I had forgotten ;). We do have logic in the there to try to be smart about the performer for the workflow rules. 

For these rules: 'a matching branch is created' and 'pull request created', and 'pull request merged into default branch' workflow rules, the user who initiated the action should be shown as the one performing the action.

The outlier rule, which doesn't work like what I've described above is the 'When an issue is closed' rule which simply uses the project creator as the adder of the label. Not ideal and have filed an issue to fix. Will keep you updated.

**Comment by CatalinaMoisuc** [comment] 2019-05-14 15:08
@arifb

It happens also to us, the logic is not that smart.

We do have a `bot user` named `A` that usually adds and removes labels.
"A" is the account that indeed is the Primary Owner, but for adding the label when an issue is closed, there is always a user `B` that is adding it.

It is really weird especially since user `B` has "Collaborator" access and also was one of the last users added to Codetree, so it really doesn't make any sense.

Also as said, for the other rules ('a matching branch is created' and 'pull request created', and 'pull request merged into default branch') we still see in the history that the Primary Owner `A` changed the labels.

**Comment by ac21** [comment] 2019-05-16 20:29
Hey @CatalinaMoisuc - I'm DMing you as I have some account specific questions I'd like to understand regarding this issue.

**Comment by ac21** [comment] 2019-11-02 03:30
closing issue as this has been addressed

**Closed as completed by ac21** 2019-11-02 03:30 UTC

**Comment by CatalinaMoisuc** [comment] 2019-11-05 08:39
@ac21 I can confirm that the problem is fixed! Thank you, it was really cluttering the PRs and issues history.
