### ISSUE TITLE
Shared shortcuts

### ISSUE THREAD

**Issue by aseemk** [codetree/feedback#66] opened 2015-03-26 16:07 UTC
It'd be great if shortcuts could be shared across the team (i.e. everyone who had access to view this project, had access to these shortcuts).

There might still be scenarios for personal shortcuts, so I'd be okay with both personal and shared shortcuts, but at least in our workflow, shared shortcuts are much more valuable than personal.

**Comment by derrickreimer** [comment] 2015-05-13 04:43
Duplicate of #48

**Closed as completed by derrickreimer** 2015-05-13 04:43 UTC
Labels: duplicate, In Review
