### ISSUE TITLE
Milestone management

### ISSUE THREAD

**Issue by lightcap** [codetree/feedback#22] opened 2015-01-07 13:41 UTC
I created new milestones in Github, but after 10 or 15 minutes they never showed up in Codetree. But, creating them in Codetree did create new milestones in Github.

Can we get some clarity on how this is intended to work? 

As part of this, how do we go about editing a milestone name so that it appears synced in both Github and Codetree?

Another corollary would be: what can we expect for syncing between Github and Codetree? How often does it happen?

There's probably 10 feature requests that could come out of this issue depending on the answers :-)

**Comment by derrickreimer** [comment] 2015-01-07 16:35
When milestones are created on GitHub, they are synced...eventually. The bummer here is that GitHub does not send webhook events for milestone creation, so we have to fall back to polling the API. We do this periodically. At present time, it could take up to a few hours for them to appear in Codetree (because load is very high right now with the recent public launch). I'm working on tightening up that time frame though, so expect that to get shorter.

The advantage of creating/closing/reopening them in Codetree, is that we will automatically update the milestone in all linked repositories (if you have a multi-repo project).

**Comment by lightcap** [comment] 2015-01-07 22:01
I've actually got milestones that seem to be completely unsynced now. My 1.3 milestone isn't showing up in Github at all, and it seems that all the tasks assigned to 1.3 have been unassigned now that the milestone is gone in GH. But, it's still showing up in Codetree.

**Comment by derrickreimer** [comment] 2015-01-07 22:28
That sounds strange. Did you create the milestone in question through GitHub or Codetree?

**Comment by lightcap** [comment] 2015-01-07 22:30
Strangely, it was there before I started using Codetree. I've been
monkeying around with both interfaces a fair amount today and it's hard to
tell what's what now.

I'll run a few tests and let you know.

**Comment by lightcap** [comment] 2015-01-08 12:08
Here's a screenshot. After an overnight there's still unsynced milestones. I need to delete the 1.3 milestone so I can continue working, so unfortunately you're not going to have the state to work off of. But, the issue is there.

It's also strange that my milestones are showing up as "edited" 14 minutes ago in Github. I haven't touched them since setting them up yesterday.

![41to1](https://cloud.githubusercontent.com/assets/12123/5662281/5c675938-9737-11e4-9615-fd62d88a34e2.png)

![n7fkr](https://cloud.githubusercontent.com/assets/12123/5662249/07347856-9737-11e4-8946-390f6f05eb59.png)

**Comment by derrickreimer** [comment] 2015-01-08 16:14
It looks like there's a bug in the two-way syncing mechanism of milestones, preventing milestones deleted on GH from being deleted in Codetree. I'll address this soon and post here when it's fixed!

**Comment by derrickreimer** [comment] 2015-01-08 16:26
For now, I manually removed that stray 1.3 milestone from your Codetree project.

**Comment by lightcap** [comment] 2015-01-08 17:18
Thanks. I just closed the other x.x style milestones because I couldn't
delete them, either. So, I think there's definitely an issue there. Should
I drop an issue in codetree/feedback to ask for the ability to delete
milestones from the Codetree interface? That would probably do the trick
here.

**Comment by derrickreimer** [comment] 2015-01-08 17:20
> Should I drop an issue in codetree/feedback to ask for the ability to delete milestones from the Codetree interface?

Sure that'd be great. Keeps the paper trail clean so you can be notified when that one is shipped. I'll still hammer out the sync bug, but native deletion capability is definitely something we need to have.

**Comment by lightcap** [comment] 2015-01-08 17:35
Sorry for so many questions, really trying to make this work for us. And,
by the way it's great. I was figuring I'd have to build this for myself
eventually so I really can't tell you how happy I am to have Codetree.

In that vein, I really need to add view only collaborators so I can get my
stakeholders to see the milestones. This is probably the 2nd most important
reason for us to use Codetree. (The first is my sanity when I'm planning
projects). But, I'm already at my max on the $49 plan. It's a big jump to
go to the next level up, and it puts the service at the same price as
Github itself for me. No matter how much I like it, it's tough to justify
that.

So, I have two options here.

1) I can move this project over to my client's organization. I don't want
to lose the work I've put in on the project, so I'd need to ask you to move
the project to the new org. (I'm assuming that billing can be set up for
each org, but I've not tried that yet).

Or,

2) I could ask you to increase the number of users in your tier and happily
convert the viewers when that feature arrives. :-)

Don't take the pricing comment as negative, I love the service so far, and
I can see that your plans are very much in line with what I need. I'm just
trying to give honest feedback on the price point and how it lines up with
the other services I use. And, I use a lot of SaaS services to run my
business. My SaaS tools budget is well over $1,000/month for reference sake. I'd
be happy to share more about the size of my team, average projects, etc if
it'll help you with your pricing strategy and direction.

Anyhow, thanks for all the quick responses.

**Comment by derrickreimer** [comment] 2015-01-08 18:04
No apology needed! This is all good stuff. I understand your predicament about the user counts. I'd be happy to work something out for upping your user count until we have client access permissions. Let's bring this conversation to email -- will follow up soon.

**Comment by lightcap** [comment] 2015-01-08 20:56
FYI, and unrelated, but none of my team members can see the project I added
them to.

**Comment by derrickreimer** [comment] 2015-01-08 20:58
Head to project Settings > Permissions -- are they in the full-access area? I'm aware of some confusion around this and will be iterating on that UI for sure :)

**Comment by lightcap** [comment] 2015-01-08 21:51
Ah! That's the issue I bet.

**Comment by lightcap** [comment] 2015-01-08 22:01
That was it. Thanks.

**Comment by VinSpee** [comment] 2015-01-09 16:27
I assume this also applies to labels. They behave the exact same way.

**Comment by jochenonline** [comment] 2015-01-09 17:13
On my side also the milestone relation of an issue is not synched from GitHub to codetree. When I change the milestone of an issue, it keeps on beeing related to the   old milestone in codetree. This happens (or better not happens) even if both milestones are known in codetree. 

Is this a bug ore a feature?

**Comment by derrickreimer** [comment] 2015-01-09 17:20
@VinSpee yes, I believe the same issue is affecting label syncing. I will address this soon.

@jochenonline that sync should happen eventually. Strangely enough, GitHub does not send webhook events when the milestone of an issue is updated, so we have to rely on polling the API for those changes. (Hopefully this will change!). I'm working on tightening up the polling frequency to get those changes in as fast as possible.

**Comment by VinSpee** [comment] 2015-01-10 00:52
In the meantime, would it be useful to have a manual syncing button? I assume this is normally not a huge issue, but it is when first setting up a repo.

**Comment by derrickreimer** [comment] 2015-01-10 05:26
@VinSpee yes, I agree.

**Comment by derrickreimer** [comment] 2015-01-11 05:30
Alright, the original problem referenced here should be fixed now: milestones (and labels) that are deleted on GitHub are now deleted in Codetree within a few hours. I'm still a fan of adding manual sync buttons in various places, though, so I will open separate issues to track those features.

**Comment by lightcap** [comment] 2015-01-11 15:46
Yeah, I'd love to see manual refresh buttons too.

Thanks for fixing this!

Also, related, I've still got a bunch of orphaned milestones. Anything in
this screenshot without a "v" in front of the milestone doesn't exist in
Github.

**Comment by derrickreimer** [comment] 2015-01-11 20:02
@lightcap should be all synced up now.

**Comment by lightcap** [comment] 2015-01-11 20:55
I just saw! Thanks :-)

**Comment by lightcap** [comment] 2015-01-11 22:31
Looks like they're back. Just taken:

**Comment by derrickreimer** [comment] 2015-01-11 22:32
@lightcap well that's mysterious...I'm on it. Sorry for the back and forth on this one.

**Comment by derrickreimer** [comment] 2015-01-11 23:07
@lightcap can you confirm that milestone number two (with the name "1.5") is deleted from the "api" repository?

**Comment by lightcap** [comment] 2015-01-12 10:27
Actually, I've got 1.4, 1.5, 1.6, and 1.7 in "closed" in Github.
Coordinating milestones between repos is going to be a challenge :-) Maybe
when there's more than one repo in a project there should be some indicator
which repo it's from?

Does creating a milestone in Codetree when there's multiple repos create
that milestone in all repos?

I'm deleting the milestones without the "v" prefix that are closed in
github juju-api right now, then.

**Comment by VinSpee** [comment] 2015-01-12 12:57
Yes I agree. There should be some indicator of which repo the issue is from. We are hacking around that right now by using a label, which is annoying.

**Comment by derrickreimer** [comment] 2015-01-16 00:56
> Coordinating milestones between repos is going to be a challenge :-) Maybe when there's more than one repo in a project there should be some indicator which repo it's from?

Yeah, it's a tricky problem. Right now, we take all milestones from all repos and bring them in as project milestones in Codetree. The idea is to not have to think about which repo has which milestones. When you move an issue under a milestone that does not yet exist on it's parent repo, we create it spontaneously. But I can see how this is challenging when trying to hunt down the source of unwanted milestones. I think the remedy for this is the ability to delete milestones (in all repos at once) through Codetree (see #25).

> Does creating a milestone in Codetree when there's multiple repos create that milestone in all repos?

Yes indeed.

> There should be some indicator of which repo the issue is from. We are hacking around that right now by using a label, which is annoying.

@VinSpee could you explain a bit more? Do you have milestones that you don't want shared between repos?

**Comment by derrickreimer** [comment] 2015-01-16 04:36
Feast your eyes!

![milestone-refresh](https://cloud.githubusercontent.com/assets/341387/5771643/0dec0e38-9cf6-11e4-99f4-0e53c6b91442.png)

/cc @VinSpee @lightcap

**Comment by lightcap** [comment] 2015-01-16 12:27
Thanks, that's great!

**Closed as completed** 2015-02-05 17:19 UTC
Labels: In Review
